// Generated by scripts/deploy.sh — do not edit by hand.
export const DEPLOYMENT = {
  address: "0xd4aC45705278Bb49aBdbF938ee596dE29fB0Be92",
  chainId: 11155111,
  chainName: "Sepolia",
  rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
  explorer: "https://sepolia.etherscan.io",
  block: 11445989,
};
