#!/usr/bin/env bash
# Deploy Deadlight and regenerate the frontend's deployment.ts.
#
#   RPC_URL=... PRIVATE_KEY=0x... ./scripts/deploy.sh "Sepolia" "https://sepolia.etherscan.io"
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHAIN_NAME="${1:-Sepolia}"
EXPLORER="${2:-https://sepolia.etherscan.io}"

: "${RPC_URL:?set RPC_URL}"
: "${PRIVATE_KEY:?set PRIVATE_KEY}"

CHAIN_ID="$(cast chain-id --rpc-url "$RPC_URL")"
DEPLOYER="$(cast wallet address --private-key "$PRIVATE_KEY")"
BAL="$(cast balance "$DEPLOYER" --rpc-url "$RPC_URL")"

echo "chain    : $CHAIN_NAME ($CHAIN_ID)"
echo "deployer : $DEPLOYER"
echo "balance  : $(cast from-wei "$BAL") ETH"
if [ "$BAL" = "0" ]; then
  echo "!! deployer has no funds — fund $DEPLOYER first" >&2
  exit 1
fi

cd "$ROOT/contracts"
OUT="$(forge create src/Deadlight.sol:Deadlight \
  --rpc-url "$RPC_URL" --private-key "$PRIVATE_KEY" --broadcast --json)"

ADDR="$(printf '%s' "$OUT" | python3 -c 'import json,sys; print(json.load(sys.stdin)["deployedTo"])')"
TXH="$(printf '%s' "$OUT" | python3 -c 'import json,sys; print(json.load(sys.stdin)["transactionHash"])')"
BLOCK="$(cast receipt "$TXH" --rpc-url "$RPC_URL" --json | python3 -c 'import json,sys; print(int(json.load(sys.stdin)["blockNumber"],16))')"

echo "deployed : $ADDR (block $BLOCK)"

cat > "$ROOT/app/src/lib/deployment.ts" <<EOF
// Generated by scripts/deploy.sh — do not edit by hand.
export const DEPLOYMENT = {
  address: "$ADDR",
  chainId: $CHAIN_ID,
  chainName: "$CHAIN_NAME",
  rpcUrl: "$RPC_URL",
  explorer: "$EXPLORER",
  block: $BLOCK,
};
EOF

echo "wrote    : app/src/lib/deployment.ts"
echo "$EXPLORER/address/$ADDR"
